"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict

from .group_0138 import (
    CodeScanningAlertLocationType,
    CodeScanningAlertLocationTypeForResponse,
)


class CodeScanningAlertInstanceType(TypedDict):
    """CodeScanningAlertInstance"""

    ref: NotRequired[str]
    analysis_key: NotRequired[str]
    environment: NotRequired[str]
    category: NotRequired[str]
    state: NotRequired[Union[Literal["open", "dismissed", "fixed"], None]]
    commit_sha: NotRequired[str]
    message: NotRequired[CodeScanningAlertInstancePropMessageType]
    location: NotRequired[CodeScanningAlertLocationType]
    html_url: NotRequired[str]
    classifications: NotRequired[
        list[
            Union[
                Literal["source", "generated", "test", "library", "documentation"], None
            ]
        ]
    ]


class CodeScanningAlertInstanceTypeForResponse(TypedDict):
    """CodeScanningAlertInstance"""

    ref: NotRequired[str]
    analysis_key: NotRequired[str]
    environment: NotRequired[str]
    category: NotRequired[str]
    state: NotRequired[Union[Literal["open", "dismissed", "fixed"], None]]
    commit_sha: NotRequired[str]
    message: NotRequired[CodeScanningAlertInstancePropMessageTypeForResponse]
    location: NotRequired[CodeScanningAlertLocationTypeForResponse]
    html_url: NotRequired[str]
    classifications: NotRequired[
        list[
            Union[
                Literal["source", "generated", "test", "library", "documentation"], None
            ]
        ]
    ]


class CodeScanningAlertInstancePropMessageType(TypedDict):
    """CodeScanningAlertInstancePropMessage"""

    text: NotRequired[str]
    markdown: NotRequired[str]


class CodeScanningAlertInstancePropMessageTypeForResponse(TypedDict):
    """CodeScanningAlertInstancePropMessage"""

    text: NotRequired[str]
    markdown: NotRequired[str]


__all__ = (
    "CodeScanningAlertInstancePropMessageType",
    "CodeScanningAlertInstancePropMessageTypeForResponse",
    "CodeScanningAlertInstanceType",
    "CodeScanningAlertInstanceTypeForResponse",
)
