"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import datetime as _dt
from typing_extensions import TypedDict


class ReposOwnerRepoCodespacesSecretsGetResponse200Type(TypedDict):
    """ReposOwnerRepoCodespacesSecretsGetResponse200"""

    total_count: int
    secrets: list[RepoCodespacesSecretType]


class ReposOwnerRepoCodespacesSecretsGetResponse200TypeForResponse(TypedDict):
    """ReposOwnerRepoCodespacesSecretsGetResponse200"""

    total_count: int
    secrets: list[RepoCodespacesSecretTypeForResponse]


class RepoCodespacesSecretType(TypedDict):
    """Codespaces Secret

    Set repository secrets for GitHub Codespaces.
    """

    name: str
    created_at: _dt.datetime
    updated_at: _dt.datetime


class RepoCodespacesSecretTypeForResponse(TypedDict):
    """Codespaces Secret

    Set repository secrets for GitHub Codespaces.
    """

    name: str
    created_at: str
    updated_at: str


__all__ = (
    "RepoCodespacesSecretType",
    "RepoCodespacesSecretTypeForResponse",
    "ReposOwnerRepoCodespacesSecretsGetResponse200Type",
    "ReposOwnerRepoCodespacesSecretsGetResponse200TypeForResponse",
)
