"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Union
from typing_extensions import NotRequired, TypedDict

from .group_0229 import (
    RepositoryRuleCreationType,
    RepositoryRuleCreationTypeForResponse,
    RepositoryRuleDeletionType,
    RepositoryRuleDeletionTypeForResponse,
    RepositoryRuleNonFastForwardType,
    RepositoryRuleNonFastForwardTypeForResponse,
    RepositoryRuleRequiredSignaturesType,
    RepositoryRuleRequiredSignaturesTypeForResponse,
)
from .group_0230 import RepositoryRuleUpdateType, RepositoryRuleUpdateTypeForResponse
from .group_0232 import (
    RepositoryRuleRequiredLinearHistoryType,
    RepositoryRuleRequiredLinearHistoryTypeForResponse,
)
from .group_0233 import (
    RepositoryRuleMergeQueueType,
    RepositoryRuleMergeQueueTypeForResponse,
)
from .group_0235 import (
    RepositoryRuleRequiredDeploymentsType,
    RepositoryRuleRequiredDeploymentsTypeForResponse,
)
from .group_0238 import (
    RepositoryRulePullRequestType,
    RepositoryRulePullRequestTypeForResponse,
)
from .group_0240 import (
    RepositoryRuleRequiredStatusChecksType,
    RepositoryRuleRequiredStatusChecksTypeForResponse,
)
from .group_0242 import (
    RepositoryRuleCommitMessagePatternType,
    RepositoryRuleCommitMessagePatternTypeForResponse,
)
from .group_0244 import (
    RepositoryRuleCommitAuthorEmailPatternType,
    RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
)
from .group_0246 import (
    RepositoryRuleCommitterEmailPatternType,
    RepositoryRuleCommitterEmailPatternTypeForResponse,
)
from .group_0248 import (
    RepositoryRuleBranchNamePatternType,
    RepositoryRuleBranchNamePatternTypeForResponse,
)
from .group_0250 import (
    RepositoryRuleTagNamePatternType,
    RepositoryRuleTagNamePatternTypeForResponse,
)
from .group_0253 import (
    RepositoryRuleWorkflowsType,
    RepositoryRuleWorkflowsTypeForResponse,
)
from .group_0255 import (
    RepositoryRuleCodeScanningType,
    RepositoryRuleCodeScanningTypeForResponse,
)
from .group_0257 import (
    RepositoryRuleCodeCoverageType,
    RepositoryRuleCodeCoverageTypeForResponse,
    RepositoryRuleCodeQualityType,
    RepositoryRuleCodeQualityTypeForResponse,
    RepositoryRuleLicenseComplianceScanningType,
    RepositoryRuleLicenseComplianceScanningTypeForResponse,
)
from .group_0258 import (
    RepositoryRuleCopilotCodeReviewType,
    RepositoryRuleCopilotCodeReviewTypeForResponse,
)
from .group_0260 import (
    RepositoryRuleFilePathRestrictionType,
    RepositoryRuleFilePathRestrictionTypeForResponse,
)
from .group_0262 import (
    RepositoryRuleMaxFilePathLengthType,
    RepositoryRuleMaxFilePathLengthTypeForResponse,
)
from .group_0264 import (
    RepositoryRuleFileExtensionRestrictionType,
    RepositoryRuleFileExtensionRestrictionTypeForResponse,
)
from .group_0266 import (
    RepositoryRuleMaxFileSizeType,
    RepositoryRuleMaxFileSizeTypeForResponse,
)
from .group_0975 import (
    WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType,
    WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsTypeForResponse,
)


class WebhookRepositoryRulesetEditedPropChangesPropRulesType(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropRules"""

    added: NotRequired[
        list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
                RepositoryRuleCodeQualityType,
                RepositoryRuleCodeCoverageType,
                RepositoryRuleCopilotCodeReviewType,
                RepositoryRuleLicenseComplianceScanningType,
                RepositoryRuleFilePathRestrictionType,
                RepositoryRuleMaxFilePathLengthType,
                RepositoryRuleFileExtensionRestrictionType,
                RepositoryRuleMaxFileSizeType,
            ]
        ]
    ]
    deleted: NotRequired[
        list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
                RepositoryRuleCodeQualityType,
                RepositoryRuleCodeCoverageType,
                RepositoryRuleCopilotCodeReviewType,
                RepositoryRuleLicenseComplianceScanningType,
                RepositoryRuleFilePathRestrictionType,
                RepositoryRuleMaxFilePathLengthType,
                RepositoryRuleFileExtensionRestrictionType,
                RepositoryRuleMaxFileSizeType,
            ]
        ]
    ]
    updated: NotRequired[
        list[WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType]
    ]


class WebhookRepositoryRulesetEditedPropChangesPropRulesTypeForResponse(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropRules"""

    added: NotRequired[
        list[
            Union[
                RepositoryRuleCreationTypeForResponse,
                RepositoryRuleUpdateTypeForResponse,
                RepositoryRuleDeletionTypeForResponse,
                RepositoryRuleRequiredLinearHistoryTypeForResponse,
                RepositoryRuleMergeQueueTypeForResponse,
                RepositoryRuleRequiredDeploymentsTypeForResponse,
                RepositoryRuleRequiredSignaturesTypeForResponse,
                RepositoryRulePullRequestTypeForResponse,
                RepositoryRuleRequiredStatusChecksTypeForResponse,
                RepositoryRuleNonFastForwardTypeForResponse,
                RepositoryRuleCommitMessagePatternTypeForResponse,
                RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
                RepositoryRuleCommitterEmailPatternTypeForResponse,
                RepositoryRuleBranchNamePatternTypeForResponse,
                RepositoryRuleTagNamePatternTypeForResponse,
                RepositoryRuleWorkflowsTypeForResponse,
                RepositoryRuleCodeScanningTypeForResponse,
                RepositoryRuleCodeQualityTypeForResponse,
                RepositoryRuleCodeCoverageTypeForResponse,
                RepositoryRuleCopilotCodeReviewTypeForResponse,
                RepositoryRuleLicenseComplianceScanningTypeForResponse,
                RepositoryRuleFilePathRestrictionTypeForResponse,
                RepositoryRuleMaxFilePathLengthTypeForResponse,
                RepositoryRuleFileExtensionRestrictionTypeForResponse,
                RepositoryRuleMaxFileSizeTypeForResponse,
            ]
        ]
    ]
    deleted: NotRequired[
        list[
            Union[
                RepositoryRuleCreationTypeForResponse,
                RepositoryRuleUpdateTypeForResponse,
                RepositoryRuleDeletionTypeForResponse,
                RepositoryRuleRequiredLinearHistoryTypeForResponse,
                RepositoryRuleMergeQueueTypeForResponse,
                RepositoryRuleRequiredDeploymentsTypeForResponse,
                RepositoryRuleRequiredSignaturesTypeForResponse,
                RepositoryRulePullRequestTypeForResponse,
                RepositoryRuleRequiredStatusChecksTypeForResponse,
                RepositoryRuleNonFastForwardTypeForResponse,
                RepositoryRuleCommitMessagePatternTypeForResponse,
                RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
                RepositoryRuleCommitterEmailPatternTypeForResponse,
                RepositoryRuleBranchNamePatternTypeForResponse,
                RepositoryRuleTagNamePatternTypeForResponse,
                RepositoryRuleWorkflowsTypeForResponse,
                RepositoryRuleCodeScanningTypeForResponse,
                RepositoryRuleCodeQualityTypeForResponse,
                RepositoryRuleCodeCoverageTypeForResponse,
                RepositoryRuleCopilotCodeReviewTypeForResponse,
                RepositoryRuleLicenseComplianceScanningTypeForResponse,
                RepositoryRuleFilePathRestrictionTypeForResponse,
                RepositoryRuleMaxFilePathLengthTypeForResponse,
                RepositoryRuleFileExtensionRestrictionTypeForResponse,
                RepositoryRuleMaxFileSizeTypeForResponse,
            ]
        ]
    ]
    updated: NotRequired[
        list[
            WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsTypeForResponse
        ]
    ]


__all__ = (
    "WebhookRepositoryRulesetEditedPropChangesPropRulesType",
    "WebhookRepositoryRulesetEditedPropChangesPropRulesTypeForResponse",
)
