"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0053 import IssueType, IssueTypeForResponse
from .group_0565 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0566 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0567 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse


class WebhookIssueRelatesToAddedType(TypedDict):
    """relates to issue added event"""

    action: Literal["relates_to_added"]
    issue_id: NotRequired[float]
    issue: NotRequired[IssueType]
    related_issue_id: NotRequired[float]
    related_issue: NotRequired[IssueType]
    installation: NotRequired[SimpleInstallationType]
    organization: OrganizationSimpleWebhooksType
    repository: RepositoryWebhooksType
    sender: SimpleUserType


class WebhookIssueRelatesToAddedTypeForResponse(TypedDict):
    """relates to issue added event"""

    action: Literal["relates_to_added"]
    issue_id: NotRequired[float]
    issue: NotRequired[IssueTypeForResponse]
    related_issue_id: NotRequired[float]
    related_issue: NotRequired[IssueTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    organization: OrganizationSimpleWebhooksTypeForResponse
    repository: RepositoryWebhooksTypeForResponse
    sender: SimpleUserTypeForResponse


__all__ = (
    "WebhookIssueRelatesToAddedType",
    "WebhookIssueRelatesToAddedTypeForResponse",
)
