from githubkit_schemas.core import LATEST_VERSION as LATEST_VERSION
from githubkit_schemas.core import VERSION_TYPE as VERSION_TYPE
from githubkit_schemas.core import VERSIONS as VERSIONS
from githubkit_schemas.core import RestVersionSwitcher as RestVersionSwitcher
from githubkit_schemas.core import WebhooksVersionSwitcher as WebhooksVersionSwitcher
