"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_1457 import (
    ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyPropAgentAssignmentType,
    ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyPropAgentAssignmentTypeForResponse,
)


class ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1Type(TypedDict):
    """ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1"""

    state: NotRequired[Literal["dismissed", "open"]]
    dismissed_reason: NotRequired[
        Literal[
            "fix_started", "inaccurate", "no_bandwidth", "not_used", "tolerable_risk"
        ]
    ]
    dismissed_comment: NotRequired[str]
    assignees: list[str]
    agent_assignment: NotRequired[
        ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyPropAgentAssignmentType
    ]


class ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1TypeForResponse(
    TypedDict
):
    """ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1"""

    state: NotRequired[Literal["dismissed", "open"]]
    dismissed_reason: NotRequired[
        Literal[
            "fix_started", "inaccurate", "no_bandwidth", "not_used", "tolerable_risk"
        ]
    ]
    dismissed_comment: NotRequired[str]
    assignees: list[str]
    agent_assignment: NotRequired[
        ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyPropAgentAssignmentTypeForResponse
    ]


__all__ = (
    "ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1Type",
    "ReposOwnerRepoDependabotAlertsAlertNumberPatchBodyAnyof1TypeForResponse",
)
