"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import NotRequired, TypedDict


class OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202Type(
    TypedDict
):
    """OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202"""

    message: NotRequired[str]
    warning: NotRequired[str]


class OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202TypeForResponse(
    TypedDict
):
    """OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202"""

    message: NotRequired[str]
    warning: NotRequired[str]


__all__ = (
    "OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202Type",
    "OrgsOrgCredentialAuthorizationsUsernameRevokeCredentialTypePostResponse202TypeForResponse",
)
