"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from typing import Dict, Type, Union
from typing_extensions import Annotated, TypeAlias

from pydantic import Field

from githubkit.compat import GitHubModel

from ..models import (
    WebhookExemptionRequestCreated,
    WebhookExemptionRequestCancelled,
    WebhookExemptionRequestCompleted,
    WebhookExemptionRequestResponseDismissed,
    WebhookExemptionRequestResponseSubmitted,
)

Event: TypeAlias = Annotated[
    Union[
        WebhookExemptionRequestCancelled,
        WebhookExemptionRequestCompleted,
        WebhookExemptionRequestCreated,
        WebhookExemptionRequestResponseDismissed,
        WebhookExemptionRequestResponseSubmitted,
    ],
    Field(discriminator="action"),
]

ExemptionRequestSecretScanningEvent: TypeAlias = Event

action_types: Dict[str, Type[GitHubModel]] = {
    "cancelled": WebhookExemptionRequestCancelled,
    "completed": WebhookExemptionRequestCompleted,
    "created": WebhookExemptionRequestCreated,
    "response_dismissed": WebhookExemptionRequestResponseDismissed,
    "response_submitted": WebhookExemptionRequestResponseSubmitted,
}

exemption_request_secret_scanning_action_types = action_types

__all__ = (
    "Event",
    "ExemptionRequestSecretScanningEvent",
    "action_types",
    "exemption_request_secret_scanning_action_types",
)
