"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from typing import Dict, Type, Union
from typing_extensions import Annotated, TypeAlias

from pydantic import Field

from githubkit.compat import GitHubModel

from ..models import (
    WebhookProjectColumnMoved,
    WebhookProjectColumnEdited,
    WebhookProjectColumnCreated,
    WebhookProjectColumnDeleted,
)

Event: TypeAlias = Annotated[
    Union[
        WebhookProjectColumnCreated,
        WebhookProjectColumnDeleted,
        WebhookProjectColumnEdited,
        WebhookProjectColumnMoved,
    ],
    Field(discriminator="action"),
]

ProjectColumnEvent: TypeAlias = Event

action_types: Dict[str, Type[GitHubModel]] = {
    "created": WebhookProjectColumnCreated,
    "deleted": WebhookProjectColumnDeleted,
    "edited": WebhookProjectColumnEdited,
    "moved": WebhookProjectColumnMoved,
}

project_column_action_types = action_types

__all__ = ("Event", "ProjectColumnEvent", "action_types", "project_column_action_types")
