"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from typing import Dict, Type, Union
from typing_extensions import Annotated, TypeAlias

from pydantic import Field

from githubkit.compat import GitHubModel

from ..models import WebhookUserCreated, WebhookUserDeleted

Event: TypeAlias = Annotated[
    Union[
        WebhookUserCreated,
        WebhookUserDeleted,
    ],
    Field(discriminator="action"),
]

UserEvent: TypeAlias = Event

action_types: Dict[str, Type[GitHubModel]] = {
    "created": WebhookUserCreated,
    "deleted": WebhookUserDeleted,
}

user_action_types = action_types

__all__ = ("Event", "UserEvent", "action_types", "user_action_types")
