"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from typing import Annotated, TypeAlias, Union

from pydantic import Field

from githubkit.compat import GitHubModel

from ..models import (
    WebhookLabelArchived,
    WebhookLabelCreated,
    WebhookLabelDeleted,
    WebhookLabelEdited,
    WebhookLabelUnarchived,
)

Event: TypeAlias = Annotated[
    Union[
        WebhookLabelArchived,
        WebhookLabelCreated,
        WebhookLabelDeleted,
        WebhookLabelEdited,
        WebhookLabelUnarchived,
    ],
    Field(discriminator="action"),
]

LabelEvent: TypeAlias = Event

action_types: dict[str, type[GitHubModel]] = {
    "archived": WebhookLabelArchived,
    "created": WebhookLabelCreated,
    "deleted": WebhookLabelDeleted,
    "edited": WebhookLabelEdited,
    "unarchived": WebhookLabelUnarchived,
}  # pyright: ignore[reportAssignmentType]

label_action_types = action_types

__all__ = ("Event", "LabelEvent", "action_types", "label_action_types")
