"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Union
from typing_extensions import NotRequired, TypedDict


class EnterprisesEnterpriseCopilotCustomAgentsGetResponse200Type(TypedDict):
    """EnterprisesEnterpriseCopilotCustomAgentsGetResponse200"""

    custom_agents: NotRequired[
        Union[
            list[
                EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsType
            ],
            None,
        ]
    ]


class EnterprisesEnterpriseCopilotCustomAgentsGetResponse200TypeForResponse(TypedDict):
    """EnterprisesEnterpriseCopilotCustomAgentsGetResponse200"""

    custom_agents: NotRequired[
        Union[
            list[
                EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsTypeForResponse
            ],
            None,
        ]
    ]


class EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsType(
    TypedDict
):
    """EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItems"""

    name: NotRequired[str]
    file_path: NotRequired[str]
    url: NotRequired[str]


class EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsTypeForResponse(
    TypedDict
):
    """EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItems"""

    name: NotRequired[str]
    file_path: NotRequired[str]
    url: NotRequired[str]


__all__ = (
    "EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsType",
    "EnterprisesEnterpriseCopilotCustomAgentsGetResponse200PropCustomAgentsItemsTypeForResponse",
    "EnterprisesEnterpriseCopilotCustomAgentsGetResponse200Type",
    "EnterprisesEnterpriseCopilotCustomAgentsGetResponse200TypeForResponse",
)
