[tool.ruff]
extend = "../pyproject.toml"
target-version = "py310"

[tool.ruff.lint]
ignore = ["TID"]

# pyright config for ci check
[tool.pyright]
extends = "../pyproject.toml"

executionEnvironments = [{ root = ".", pythonVersion = "3.10" }]
