"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Union
from typing_extensions import NotRequired, TypedDict

from .group_0196 import (
    RepositoryRuleCreationType,
    RepositoryRuleCreationTypeForResponse,
    RepositoryRuleDeletionType,
    RepositoryRuleDeletionTypeForResponse,
    RepositoryRuleNonFastForwardType,
    RepositoryRuleNonFastForwardTypeForResponse,
    RepositoryRuleRequiredSignaturesType,
    RepositoryRuleRequiredSignaturesTypeForResponse,
)
from .group_0197 import RepositoryRuleUpdateType, RepositoryRuleUpdateTypeForResponse
from .group_0199 import (
    RepositoryRuleRequiredLinearHistoryType,
    RepositoryRuleRequiredLinearHistoryTypeForResponse,
)
from .group_0200 import (
    RepositoryRuleMergeQueueType,
    RepositoryRuleMergeQueueTypeForResponse,
)
from .group_0202 import (
    RepositoryRuleRequiredDeploymentsType,
    RepositoryRuleRequiredDeploymentsTypeForResponse,
)
from .group_0204 import (
    RepositoryRulePullRequestType,
    RepositoryRulePullRequestTypeForResponse,
)
from .group_0206 import (
    RepositoryRuleRequiredStatusChecksType,
    RepositoryRuleRequiredStatusChecksTypeForResponse,
)
from .group_0208 import (
    RepositoryRuleCommitMessagePatternType,
    RepositoryRuleCommitMessagePatternTypeForResponse,
)
from .group_0210 import (
    RepositoryRuleCommitAuthorEmailPatternType,
    RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
)
from .group_0212 import (
    RepositoryRuleCommitterEmailPatternType,
    RepositoryRuleCommitterEmailPatternTypeForResponse,
)
from .group_0214 import (
    RepositoryRuleBranchNamePatternType,
    RepositoryRuleBranchNamePatternTypeForResponse,
)
from .group_0216 import (
    RepositoryRuleTagNamePatternType,
    RepositoryRuleTagNamePatternTypeForResponse,
)
from .group_0218 import (
    RepositoryRuleFilePathRestrictionType,
    RepositoryRuleFilePathRestrictionTypeForResponse,
)
from .group_0220 import (
    RepositoryRuleMaxFilePathLengthType,
    RepositoryRuleMaxFilePathLengthTypeForResponse,
)
from .group_0222 import (
    RepositoryRuleFileExtensionRestrictionType,
    RepositoryRuleFileExtensionRestrictionTypeForResponse,
)
from .group_0224 import (
    RepositoryRuleMaxFileSizeType,
    RepositoryRuleMaxFileSizeTypeForResponse,
)
from .group_0227 import (
    RepositoryRuleWorkflowsType,
    RepositoryRuleWorkflowsTypeForResponse,
)
from .group_0229 import (
    RepositoryRuleCodeScanningType,
    RepositoryRuleCodeScanningTypeForResponse,
)
from .group_0231 import (
    RepositoryRuleCopilotCodeReviewType,
    RepositoryRuleCopilotCodeReviewTypeForResponse,
)
from .group_0856 import (
    WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType,
    WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsTypeForResponse,
)


class WebhookRepositoryRulesetEditedPropChangesPropRulesType(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropRules"""

    added: NotRequired[
        list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleFilePathRestrictionType,
                RepositoryRuleMaxFilePathLengthType,
                RepositoryRuleFileExtensionRestrictionType,
                RepositoryRuleMaxFileSizeType,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
                RepositoryRuleCopilotCodeReviewType,
            ]
        ]
    ]
    deleted: NotRequired[
        list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleFilePathRestrictionType,
                RepositoryRuleMaxFilePathLengthType,
                RepositoryRuleFileExtensionRestrictionType,
                RepositoryRuleMaxFileSizeType,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
                RepositoryRuleCopilotCodeReviewType,
            ]
        ]
    ]
    updated: NotRequired[
        list[WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType]
    ]


class WebhookRepositoryRulesetEditedPropChangesPropRulesTypeForResponse(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropRules"""

    added: NotRequired[
        list[
            Union[
                RepositoryRuleCreationTypeForResponse,
                RepositoryRuleUpdateTypeForResponse,
                RepositoryRuleDeletionTypeForResponse,
                RepositoryRuleRequiredLinearHistoryTypeForResponse,
                RepositoryRuleMergeQueueTypeForResponse,
                RepositoryRuleRequiredDeploymentsTypeForResponse,
                RepositoryRuleRequiredSignaturesTypeForResponse,
                RepositoryRulePullRequestTypeForResponse,
                RepositoryRuleRequiredStatusChecksTypeForResponse,
                RepositoryRuleNonFastForwardTypeForResponse,
                RepositoryRuleCommitMessagePatternTypeForResponse,
                RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
                RepositoryRuleCommitterEmailPatternTypeForResponse,
                RepositoryRuleBranchNamePatternTypeForResponse,
                RepositoryRuleTagNamePatternTypeForResponse,
                RepositoryRuleFilePathRestrictionTypeForResponse,
                RepositoryRuleMaxFilePathLengthTypeForResponse,
                RepositoryRuleFileExtensionRestrictionTypeForResponse,
                RepositoryRuleMaxFileSizeTypeForResponse,
                RepositoryRuleWorkflowsTypeForResponse,
                RepositoryRuleCodeScanningTypeForResponse,
                RepositoryRuleCopilotCodeReviewTypeForResponse,
            ]
        ]
    ]
    deleted: NotRequired[
        list[
            Union[
                RepositoryRuleCreationTypeForResponse,
                RepositoryRuleUpdateTypeForResponse,
                RepositoryRuleDeletionTypeForResponse,
                RepositoryRuleRequiredLinearHistoryTypeForResponse,
                RepositoryRuleMergeQueueTypeForResponse,
                RepositoryRuleRequiredDeploymentsTypeForResponse,
                RepositoryRuleRequiredSignaturesTypeForResponse,
                RepositoryRulePullRequestTypeForResponse,
                RepositoryRuleRequiredStatusChecksTypeForResponse,
                RepositoryRuleNonFastForwardTypeForResponse,
                RepositoryRuleCommitMessagePatternTypeForResponse,
                RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
                RepositoryRuleCommitterEmailPatternTypeForResponse,
                RepositoryRuleBranchNamePatternTypeForResponse,
                RepositoryRuleTagNamePatternTypeForResponse,
                RepositoryRuleFilePathRestrictionTypeForResponse,
                RepositoryRuleMaxFilePathLengthTypeForResponse,
                RepositoryRuleFileExtensionRestrictionTypeForResponse,
                RepositoryRuleMaxFileSizeTypeForResponse,
                RepositoryRuleWorkflowsTypeForResponse,
                RepositoryRuleCodeScanningTypeForResponse,
                RepositoryRuleCopilotCodeReviewTypeForResponse,
            ]
        ]
    ]
    updated: NotRequired[
        list[
            WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsTypeForResponse
        ]
    ]


__all__ = (
    "WebhookRepositoryRulesetEditedPropChangesPropRulesType",
    "WebhookRepositoryRulesetEditedPropChangesPropRulesTypeForResponse",
)
