"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Literal, overload
from weakref import ref

from pydantic import BaseModel

from githubkit.compat import model_dump, type_validate_python
from githubkit.typing import Missing, UnsetType
from githubkit.utils import UNSET, exclude_unset, parse_query_params

if TYPE_CHECKING:
    from typing import Literal, Union

    from githubkit import GitHubCore
    from githubkit.response import Response
    from githubkit.typing import Missing
    from githubkit.utils import UNSET

    from ..models import CodeQualityFinding, CodeQualitySetup, EmptyObject
    from ..types import (
        CodeQualityFindingTypeForResponse,
        CodeQualitySetupTypeForResponse,
        CodeQualitySetupUpdateAnyof0Type,
        CodeQualitySetupUpdateAnyof1Type,
        CodeQualitySetupUpdateAnyof2Type,
        CodeQualitySetupUpdateAnyof3Type,
        EmptyObjectTypeForResponse,
    )


class CodeQualityClient:
    _REST_API_VERSION = "2022-11-28"

    def __init__(self, github: GitHubCore):
        self._github_ref = ref(github)

    @property
    def _github(self) -> GitHubCore:
        if g := self._github_ref():
            return g
        raise RuntimeError(
            "GitHub client has already been collected. "
            "Do not use this client after the client has been collected."
        )

    def list_findings_for_repo(
        self,
        owner: str,
        repo: str,
        *,
        per_page: Missing[int] = UNSET,
        direction: Missing[Literal["asc", "desc"]] = UNSET,
        before: Missing[str] = UNSET,
        after: Missing[str] = UNSET,
        state: Missing[Literal["open", "dismissed"]] = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[list[CodeQualityFinding], list[CodeQualityFindingTypeForResponse]]:
        """code-quality/list-findings-for-repo

        GET /repos/{owner}/{repo}/code-quality/findings

        Lists code quality findings for a repository.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#list-code-quality-findings-for-a-repository
        """

        from ..models import BasicError, CodeQualityFinding, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/findings"

        params = {
            "per_page": per_page,
            "direction": direction,
            "before": before,
            "after": after,
            "state": state,
        }

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return self._github.request(
            "GET",
            url,
            params=exclude_unset(parse_query_params(params)),
            headers=exclude_unset(headers),
            stream=stream,
            response_model=list[CodeQualityFinding],
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    async def async_list_findings_for_repo(
        self,
        owner: str,
        repo: str,
        *,
        per_page: Missing[int] = UNSET,
        direction: Missing[Literal["asc", "desc"]] = UNSET,
        before: Missing[str] = UNSET,
        after: Missing[str] = UNSET,
        state: Missing[Literal["open", "dismissed"]] = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[list[CodeQualityFinding], list[CodeQualityFindingTypeForResponse]]:
        """code-quality/list-findings-for-repo

        GET /repos/{owner}/{repo}/code-quality/findings

        Lists code quality findings for a repository.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#list-code-quality-findings-for-a-repository
        """

        from ..models import BasicError, CodeQualityFinding, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/findings"

        params = {
            "per_page": per_page,
            "direction": direction,
            "before": before,
            "after": after,
            "state": state,
        }

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return await self._github.arequest(
            "GET",
            url,
            params=exclude_unset(parse_query_params(params)),
            headers=exclude_unset(headers),
            stream=stream,
            response_model=list[CodeQualityFinding],
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    def get_finding(
        self,
        owner: str,
        repo: str,
        finding_number: int,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[CodeQualityFinding, CodeQualityFindingTypeForResponse]:
        """code-quality/get-finding

        GET /repos/{owner}/{repo}/code-quality/findings/{finding_number}

        Gets a single code quality finding.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#get-a-code-quality-finding
        """

        from ..models import BasicError, CodeQualityFinding, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/findings/{finding_number}"

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return self._github.request(
            "GET",
            url,
            headers=exclude_unset(headers),
            stream=stream,
            response_model=CodeQualityFinding,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    async def async_get_finding(
        self,
        owner: str,
        repo: str,
        finding_number: int,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[CodeQualityFinding, CodeQualityFindingTypeForResponse]:
        """code-quality/get-finding

        GET /repos/{owner}/{repo}/code-quality/findings/{finding_number}

        Gets a single code quality finding.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#get-a-code-quality-finding
        """

        from ..models import BasicError, CodeQualityFinding, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/findings/{finding_number}"

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return await self._github.arequest(
            "GET",
            url,
            headers=exclude_unset(headers),
            stream=stream,
            response_model=CodeQualityFinding,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    def get_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[CodeQualitySetup, CodeQualitySetupTypeForResponse]:
        """code-quality/get-setup

        GET /repos/{owner}/{repo}/code-quality/setup

        Gets a code quality setup configuration.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#get-a-code-quality-setup-configuration
        """

        from ..models import BasicError, CodeQualitySetup, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/setup"

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return self._github.request(
            "GET",
            url,
            headers=exclude_unset(headers),
            stream=stream,
            response_model=CodeQualitySetup,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    async def async_get_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
    ) -> Response[CodeQualitySetup, CodeQualitySetupTypeForResponse]:
        """code-quality/get-setup

        GET /repos/{owner}/{repo}/code-quality/setup

        Gets a code quality setup configuration.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#get-a-code-quality-setup-configuration
        """

        from ..models import BasicError, CodeQualitySetup, EventsGetResponse503

        url = f"/repos/{owner}/{repo}/code-quality/setup"

        headers = {"X-GitHub-Api-Version": self._REST_API_VERSION, **(headers or {})}

        return await self._github.arequest(
            "GET",
            url,
            headers=exclude_unset(headers),
            stream=stream,
            response_model=CodeQualitySetup,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "503": EventsGetResponse503,
            },
        )

    @overload
    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        data: Union[
            CodeQualitySetupUpdateAnyof0Type,
            CodeQualitySetupUpdateAnyof1Type,
            CodeQualitySetupUpdateAnyof2Type,
            CodeQualitySetupUpdateAnyof3Type,
        ],
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Literal["configured", "not-configured"],
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Literal["standard", "labeled"],
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Union[str, None],
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: list[
            Literal[
                "csharp", "go", "java-kotlin", "javascript-typescript", "python", "ruby"
            ]
        ],
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    def update_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        data: Missing[
            Union[
                CodeQualitySetupUpdateAnyof0Type,
                CodeQualitySetupUpdateAnyof1Type,
                CodeQualitySetupUpdateAnyof2Type,
                CodeQualitySetupUpdateAnyof3Type,
            ]
        ] = UNSET,
        **kwargs,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]:
        """code-quality/update-setup

        PATCH /repos/{owner}/{repo}/code-quality/setup

        Updates a code quality setup configuration.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#update-a-code-quality-setup-configuration
        """

        from typing import Union

        from ..models import (
            BasicError,
            CodeQualitySetupUpdateAnyof0,
            CodeQualitySetupUpdateAnyof1,
            CodeQualitySetupUpdateAnyof2,
            CodeQualitySetupUpdateAnyof3,
            EmptyObject,
            EventsGetResponse503,
        )

        url = f"/repos/{owner}/{repo}/code-quality/setup"

        headers = {
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": self._REST_API_VERSION,
            **(headers or {}),
        }

        json = kwargs if data is UNSET else data
        if self._github.config.rest_api_validate_body:
            json = type_validate_python(
                Union[
                    CodeQualitySetupUpdateAnyof0,
                    CodeQualitySetupUpdateAnyof1,
                    CodeQualitySetupUpdateAnyof2,
                    CodeQualitySetupUpdateAnyof3,
                ],
                json,
            )
        json = model_dump(json) if isinstance(json, BaseModel) else json

        return self._github.request(
            "PATCH",
            url,
            json=exclude_unset(json),
            headers=exclude_unset(headers),
            stream=stream,
            response_model=EmptyObject,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "409": BasicError,
                "422": BasicError,
                "503": EventsGetResponse503,
            },
        )

    @overload
    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        data: Union[
            CodeQualitySetupUpdateAnyof0Type,
            CodeQualitySetupUpdateAnyof1Type,
            CodeQualitySetupUpdateAnyof2Type,
            CodeQualitySetupUpdateAnyof3Type,
        ],
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Literal["configured", "not-configured"],
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Literal["standard", "labeled"],
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Union[str, None],
        languages: Missing[
            list[
                Literal[
                    "csharp",
                    "go",
                    "java-kotlin",
                    "javascript-typescript",
                    "python",
                    "ruby",
                ]
            ]
        ] = UNSET,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    @overload
    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        data: UnsetType = UNSET,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        state: Missing[Literal["configured", "not-configured"]] = UNSET,
        runner_type: Missing[Literal["standard", "labeled"]] = UNSET,
        runner_label: Missing[Union[str, None]] = UNSET,
        languages: list[
            Literal[
                "csharp", "go", "java-kotlin", "javascript-typescript", "python", "ruby"
            ]
        ],
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]: ...

    async def async_update_setup(
        self,
        owner: str,
        repo: str,
        *,
        headers: Mapping[str, str] | None = None,
        stream: bool = False,
        data: Missing[
            Union[
                CodeQualitySetupUpdateAnyof0Type,
                CodeQualitySetupUpdateAnyof1Type,
                CodeQualitySetupUpdateAnyof2Type,
                CodeQualitySetupUpdateAnyof3Type,
            ]
        ] = UNSET,
        **kwargs,
    ) -> Response[EmptyObject, EmptyObjectTypeForResponse]:
        """code-quality/update-setup

        PATCH /repos/{owner}/{repo}/code-quality/setup

        Updates a code quality setup configuration.

        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.

        See also: https://docs.github.com/rest/code-quality/code-quality#update-a-code-quality-setup-configuration
        """

        from typing import Union

        from ..models import (
            BasicError,
            CodeQualitySetupUpdateAnyof0,
            CodeQualitySetupUpdateAnyof1,
            CodeQualitySetupUpdateAnyof2,
            CodeQualitySetupUpdateAnyof3,
            EmptyObject,
            EventsGetResponse503,
        )

        url = f"/repos/{owner}/{repo}/code-quality/setup"

        headers = {
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": self._REST_API_VERSION,
            **(headers or {}),
        }

        json = kwargs if data is UNSET else data
        if self._github.config.rest_api_validate_body:
            json = type_validate_python(
                Union[
                    CodeQualitySetupUpdateAnyof0,
                    CodeQualitySetupUpdateAnyof1,
                    CodeQualitySetupUpdateAnyof2,
                    CodeQualitySetupUpdateAnyof3,
                ],
                json,
            )
        json = model_dump(json) if isinstance(json, BaseModel) else json

        return await self._github.arequest(
            "PATCH",
            url,
            json=exclude_unset(json),
            headers=exclude_unset(headers),
            stream=stream,
            response_model=EmptyObject,
            error_models={
                "403": BasicError,
                "404": BasicError,
                "409": BasicError,
                "422": BasicError,
                "503": EventsGetResponse503,
            },
        )
