"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import datetime as _dt
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict


class AgentsReposOwnerRepoTasksGetResponse200Type(TypedDict):
    """AgentsReposOwnerRepoTasksGetResponse200"""

    tasks: list[AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsType]
    total_active_count: NotRequired[int]
    total_archived_count: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200TypeForResponse(TypedDict):
    """AgentsReposOwnerRepoTasksGetResponse200"""

    tasks: list[AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsTypeForResponse]
    total_active_count: NotRequired[int]
    total_archived_count: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsType(TypedDict):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItems"""

    id: str
    url: NotRequired[str]
    html_url: NotRequired[str]
    name: NotRequired[str]
    creator: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0Type
    ]
    creator_type: NotRequired[Literal["user", "organization"]]
    user_collaborators: NotRequired[
        list[
            AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsType
        ]
    ]
    owner: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerType
    ]
    repository: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryType
    ]
    state: Literal[
        "queued",
        "in_progress",
        "completed",
        "failed",
        "idle",
        "waiting_for_user",
        "timed_out",
        "cancelled",
    ]
    session_count: NotRequired[int]
    artifacts: NotRequired[
        list[
            AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsType
        ]
    ]
    archived_at: NotRequired[Union[_dt.datetime, None]]
    updated_at: NotRequired[_dt.datetime]
    created_at: _dt.datetime


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsTypeForResponse(TypedDict):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItems"""

    id: str
    url: NotRequired[str]
    html_url: NotRequired[str]
    name: NotRequired[str]
    creator: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0TypeForResponse
    ]
    creator_type: NotRequired[Literal["user", "organization"]]
    user_collaborators: NotRequired[
        list[
            AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsTypeForResponse
        ]
    ]
    owner: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerTypeForResponse
    ]
    repository: NotRequired[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryTypeForResponse
    ]
    state: Literal[
        "queued",
        "in_progress",
        "completed",
        "failed",
        "idle",
        "waiting_for_user",
        "timed_out",
        "cancelled",
    ]
    session_count: NotRequired[int]
    artifacts: NotRequired[
        list[
            AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsTypeForResponse
        ]
    ]
    archived_at: NotRequired[Union[str, None]]
    updated_at: NotRequired[str]
    created_at: str


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0Type(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0

    A GitHub user
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0TypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0

    A GitHub user
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsType(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItems

    A GitHub user
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsTypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItems

    A GitHub user
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerType(TypedDict):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwner

    The owner of the repository
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerTypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwner

    The owner of the repository
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryType(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepository

    The repository this task belongs to
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryTypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepository

    The repository this task belongs to
    """

    id: NotRequired[int]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsType(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItems

    A resource generated by the task
    """

    provider: Literal["github"]
    type: Literal["github_resource", "branch"]
    data: Union[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0Type,
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1Type,
    ]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsTypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItems

    A resource generated by the task
    """

    provider: Literal["github"]
    type: Literal["github_resource", "branch"]
    data: Union[
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0TypeForResponse,
        AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1TypeForResponse,
    ]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0Type(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataO
    neof0

    A GitHub resource (pull request, issue, etc.)
    """

    id: NotRequired[int]
    type: NotRequired[str]
    global_id: NotRequired[str]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0TypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataO
    neof0

    A GitHub resource (pull request, issue, etc.)
    """

    id: NotRequired[int]
    type: NotRequired[str]
    global_id: NotRequired[str]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1Type(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataO
    neof1

    A Git branch reference
    """

    head_ref: NotRequired[str]
    base_ref: NotRequired[str]


class AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1TypeForResponse(
    TypedDict
):
    """AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataO
    neof1

    A Git branch reference
    """

    head_ref: NotRequired[str]
    base_ref: NotRequired[str]


__all__ = (
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0Type",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof0TypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1Type",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsPropDataOneof1TypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsType",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropArtifactsItemsTypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0Type",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropCreatorOneof0TypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerType",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropOwnerTypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryType",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropRepositoryTypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsType",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsPropUserCollaboratorsItemsTypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsType",
    "AgentsReposOwnerRepoTasksGetResponse200PropTasksItemsTypeForResponse",
    "AgentsReposOwnerRepoTasksGetResponse200Type",
    "AgentsReposOwnerRepoTasksGetResponse200TypeForResponse",
)
