"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild


class ActionsHostedRunnerImage(GitHubModel):
    """GitHub-hosted runner image details.

    Provides details of a hosted runner image
    """

    id: str = Field(
        description="The ID of the image. Use this ID for the `image` parameter when creating a new larger runner."
    )
    platform: str = Field(description="The operating system of the image.")
    size_gb: int = Field(description="Image size in GB.")
    display_name: str = Field(description="Display name for this image.")
    source: Literal["github", "partner", "custom"] = Field(
        description="The image provider."
    )


model_rebuild(ActionsHostedRunnerImage)

__all__ = ("ActionsHostedRunnerImage",)
