"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import PYDANTIC_V2, GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET


class OrgsOrgAttestationsBulkListPostBody(GitHubModel):
    """OrgsOrgAttestationsBulkListPostBody"""

    subject_digests: list[str] = Field(
        max_length=1024 if PYDANTIC_V2 else None,
        min_length=1 if PYDANTIC_V2 else None,
        description="List of subject digests to fetch attestations for.",
    )
    predicate_type: Missing[str] = Field(
        default=UNSET,
        description="Optional filter for fetching attestations with a given predicate type.\nThis option accepts `provenance`, `sbom`, or freeform text for custom predicate types.",
    )


model_rebuild(OrgsOrgAttestationsBulkListPostBody)

__all__ = ("OrgsOrgAttestationsBulkListPostBody",)
