"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild


class ActionsArtifactAndLogRetentionResponse(GitHubModel):
    """ActionsArtifactAndLogRetentionResponse"""

    days: int = Field(description="The number of days artifacts and logs are retained")
    maximum_allowed_days: int = Field(
        description="The maximum number of days that can be configured"
    )


model_rebuild(ActionsArtifactAndLogRetentionResponse)

__all__ = ("ActionsArtifactAndLogRetentionResponse",)
