"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

python -m codegen && isort . && black .

See https://github.com/github/rest-api-description for more information.
"""


from __future__ import annotations

from datetime import datetime
from typing import List, Union, Literal

from pydantic import Field

from githubkit.utils import UNSET
from githubkit.typing import Missing
from githubkit.compat import GitHubModel, model_rebuild

from .group_0017 import Repository


class StarredRepository(GitHubModel):
    """Starred Repository

    Starred Repository
    """

    starred_at: datetime = Field()
    repo: Repository = Field(title="Repository", description="A repository on GitHub.")


model_rebuild(StarredRepository)

__all__ = ("StarredRepository",)
