"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict


class ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2Type(TypedDict):
    """ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2"""

    state: NotRequired[Literal["open", "resolved"]]
    resolution: NotRequired[
        Union[None, Literal["false_positive", "wont_fix", "revoked", "used_in_tests"]]
    ]
    resolution_comment: NotRequired[Union[str, None]]
    assignee: NotRequired[Union[str, None]]
    validity: Union[None, Literal["active", "inactive"]]


class ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2TypeForResponse(
    TypedDict
):
    """ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2"""

    state: NotRequired[Literal["open", "resolved"]]
    resolution: NotRequired[
        Union[None, Literal["false_positive", "wont_fix", "revoked", "used_in_tests"]]
    ]
    resolution_comment: NotRequired[Union[str, None]]
    assignee: NotRequired[Union[str, None]]
    validity: Union[None, Literal["active", "inactive"]]


__all__ = (
    "ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2Type",
    "ReposOwnerRepoSecretScanningAlertsAlertNumberPatchBodyAnyof2TypeForResponse",
)
