"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from .group_0122 import (
    ActionsPolicyWorkflowPathConditionPropWorkflowPathType,
    ActionsPolicyWorkflowPathConditionPropWorkflowPathTypeForResponse,
)
from .group_0130 import (
    RepositoryRulesetConditionsRepositoryPropertyTargetPropRepositoryPropertyType,
    RepositoryRulesetConditionsRepositoryPropertyTargetPropRepositoryPropertyTypeForResponse,
)


class ActionsPolicyOrgConditionsOneof2Type(TypedDict):
    """ActionsPolicyOrgConditionsOneof2"""

    repository_property: (
        RepositoryRulesetConditionsRepositoryPropertyTargetPropRepositoryPropertyType
    )
    workflow_path: NotRequired[ActionsPolicyWorkflowPathConditionPropWorkflowPathType]


class ActionsPolicyOrgConditionsOneof2TypeForResponse(TypedDict):
    """ActionsPolicyOrgConditionsOneof2"""

    repository_property: RepositoryRulesetConditionsRepositoryPropertyTargetPropRepositoryPropertyTypeForResponse
    workflow_path: NotRequired[
        ActionsPolicyWorkflowPathConditionPropWorkflowPathTypeForResponse
    ]


__all__ = (
    "ActionsPolicyOrgConditionsOneof2Type",
    "ActionsPolicyOrgConditionsOneof2TypeForResponse",
)
