"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild


class OrganizationFineGrainedPermission(GitHubModel):
    """Organization Fine-Grained Permission

    A fine-grained permission that protects organization resources.
    """

    name: str = Field()
    description: str = Field()


model_rebuild(OrganizationFineGrainedPermission)

__all__ = ("OrganizationFineGrainedPermission",)
