"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import PYDANTIC_V2, GitHubModel, model_rebuild

from .group_0098 import OrganizationCustomProperty


class EnterprisesEnterpriseOrgPropertiesSchemaPatchBody(GitHubModel):
    """EnterprisesEnterpriseOrgPropertiesSchemaPatchBody"""

    properties: list[OrganizationCustomProperty] = Field(
        max_length=100 if PYDANTIC_V2 else None,
        min_length=1 if PYDANTIC_V2 else None,
        description="The array of organization custom properties to create or update.",
    )


model_rebuild(EnterprisesEnterpriseOrgPropertiesSchemaPatchBody)

__all__ = ("EnterprisesEnterpriseOrgPropertiesSchemaPatchBody",)
