"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild


class GetCostCenter(GitHubModel):
    """GetCostCenter"""

    id: str = Field(description="ID of the cost center.")
    name: str = Field(description="Name of the cost center.")
    resources: list[GetCostCenterPropResourcesItems] = Field()


class GetCostCenterPropResourcesItems(GitHubModel):
    """GetCostCenterPropResourcesItems"""

    type: str = Field(description="Type of the resource.")
    name: str = Field(description="Name of the resource.")


model_rebuild(GetCostCenter)
model_rebuild(GetCostCenterPropResourcesItems)

__all__ = (
    "GetCostCenter",
    "GetCostCenterPropResourcesItems",
)
