"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET


class OrganizationCustomOrganizationRoleCreateSchema(GitHubModel):
    """OrganizationCustomOrganizationRoleCreateSchema"""

    name: str = Field(description="The name of the custom role.")
    description: Missing[str] = Field(
        default=UNSET,
        description="A short description about the intended usage of this role or what permissions it grants.",
    )
    permissions: list[str] = Field(
        description="A list of additional permissions included in this role."
    )
    base_role: Missing[Literal["read", "triage", "write", "maintain", "admin"]] = Field(
        default=UNSET,
        description="The system role from which this role can inherit permissions.",
    )


model_rebuild(OrganizationCustomOrganizationRoleCreateSchema)

__all__ = ("OrganizationCustomOrganizationRoleCreateSchema",)
