"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Literal

from pydantic import Field

from githubkit.utils import UNSET
from githubkit.typing import Missing
from githubkit.compat import GitHubModel, model_rebuild


class ReposOwnerRepoActionsWorkflowsGetResponse200(GitHubModel):
    """ReposOwnerRepoActionsWorkflowsGetResponse200"""

    total_count: int = Field()
    workflows: List[Workflow] = Field()


class Workflow(GitHubModel):
    """Workflow

    A GitHub Actions workflow
    """

    id: int = Field()
    node_id: str = Field()
    name: str = Field()
    path: str = Field()
    state: Literal[
        "active", "deleted", "disabled_fork", "disabled_inactivity", "disabled_manually"
    ] = Field()
    created_at: datetime = Field()
    updated_at: datetime = Field()
    url: str = Field()
    html_url: str = Field()
    badge_url: str = Field()
    deleted_at: Missing[datetime] = Field(default=UNSET)


model_rebuild(ReposOwnerRepoActionsWorkflowsGetResponse200)
model_rebuild(Workflow)

__all__ = (
    "ReposOwnerRepoActionsWorkflowsGetResponse200",
    "Workflow",
)
