"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET

from .group_0260 import SecretScanningCustomPattern


class OrgsOrgSecretScanningCustomPatternsPostResponse201(GitHubModel):
    """OrgsOrgSecretScanningCustomPatternsPostResponse201"""

    created_patterns: Missing[list[SecretScanningCustomPattern]] = Field(
        default=UNSET, description="The list of successfully created custom patterns."
    )


model_rebuild(OrgsOrgSecretScanningCustomPatternsPostResponse201)

__all__ = ("OrgsOrgSecretScanningCustomPatternsPostResponse201",)
