name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  env-dir:
    description: Environment directory
    required: true
  no-root:
    description: Do not install package in the environment
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: ./.github/actions/setup-poetry

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: "poetry"
        cache-dependency-path:
          - "./poetry.lock"
          - "${{ inputs.env-dir }}/poetry.lock"

    - if: ${{ inputs.no-root == "true" }}
      run: |
        cd ${{ inputs.env-dir }}
        poetry install --all-extras --no-root
      shell: bash

    - if: ${{ inputs.no-root == "false" }}
      run: |
        cd ${{ inputs.env-dir }}
        poetry install --all-extras
      shell: bash
