"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0040 import MilestoneType, MilestoneTypeForResponse
from .group_0448 import EnterpriseWebhooksType, EnterpriseWebhooksTypeForResponse
from .group_0450 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0451 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse
from .group_0486 import WebhooksPullRequest5Type, WebhooksPullRequest5TypeForResponse


class WebhookPullRequestMilestonedType(TypedDict):
    """pull_request milestoned event"""

    action: Literal["milestoned"]
    enterprise: NotRequired[EnterpriseWebhooksType]
    milestone: NotRequired[MilestoneType]
    number: int
    organization: NotRequired[OrganizationSimpleWebhooksType]
    pull_request: WebhooksPullRequest5Type
    repository: RepositoryWebhooksType
    sender: NotRequired[SimpleUserType]


class WebhookPullRequestMilestonedTypeForResponse(TypedDict):
    """pull_request milestoned event"""

    action: Literal["milestoned"]
    enterprise: NotRequired[EnterpriseWebhooksTypeForResponse]
    milestone: NotRequired[MilestoneTypeForResponse]
    number: int
    organization: NotRequired[OrganizationSimpleWebhooksTypeForResponse]
    pull_request: WebhooksPullRequest5TypeForResponse
    repository: RepositoryWebhooksTypeForResponse
    sender: NotRequired[SimpleUserTypeForResponse]


__all__ = (
    "WebhookPullRequestMilestonedType",
    "WebhookPullRequestMilestonedTypeForResponse",
)
