"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0173 import CustomPropertyValueType, CustomPropertyValueTypeForResponse
from .group_0475 import EnterpriseWebhooksType, EnterpriseWebhooksTypeForResponse
from .group_0476 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0477 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0478 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse


class WebhookCustomPropertyValuesUpdatedType(TypedDict):
    """Custom property values updated event"""

    action: Literal["updated"]
    enterprise: NotRequired[EnterpriseWebhooksType]
    installation: NotRequired[SimpleInstallationType]
    repository: RepositoryWebhooksType
    organization: OrganizationSimpleWebhooksType
    sender: NotRequired[SimpleUserType]
    new_property_values: list[CustomPropertyValueType]
    old_property_values: list[CustomPropertyValueType]


class WebhookCustomPropertyValuesUpdatedTypeForResponse(TypedDict):
    """Custom property values updated event"""

    action: Literal["updated"]
    enterprise: NotRequired[EnterpriseWebhooksTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    repository: RepositoryWebhooksTypeForResponse
    organization: OrganizationSimpleWebhooksTypeForResponse
    sender: NotRequired[SimpleUserTypeForResponse]
    new_property_values: list[CustomPropertyValueTypeForResponse]
    old_property_values: list[CustomPropertyValueTypeForResponse]


__all__ = (
    "WebhookCustomPropertyValuesUpdatedType",
    "WebhookCustomPropertyValuesUpdatedTypeForResponse",
)
