"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

python -m codegen && isort . && black .

See https://github.com/github/rest-api-description for more information.
"""


from __future__ import annotations

from typing import List, Union, Literal
from typing_extensions import TypedDict, NotRequired

from .group_0106 import RepositoryRuleUpdateType
from .group_0125 import RepositoryRuleWorkflowsType
from .group_0111 import RepositoryRulePullRequestType
from .group_0103 import OrgRulesetConditionsOneof0Type
from .group_0104 import OrgRulesetConditionsOneof1Type
from .group_0096 import RepositoryRulesetBypassActorType
from .group_0123 import RepositoryRuleTagNamePatternType
from .group_0121 import RepositoryRuleBranchNamePatternType
from .group_0109 import RepositoryRuleRequiredDeploymentsType
from .group_0113 import RepositoryRuleRequiredStatusChecksType
from .group_0115 import RepositoryRuleCommitMessagePatternType
from .group_0108 import RepositoryRuleRequiredLinearHistoryType
from .group_0119 import RepositoryRuleCommitterEmailPatternType
from .group_0117 import RepositoryRuleCommitAuthorEmailPatternType
from .group_0105 import (
    RepositoryRuleCreationType,
    RepositoryRuleDeletionType,
    RepositoryRuleNonFastForwardType,
    RepositoryRuleRequiredSignaturesType,
)


class OrgsOrgRulesetsPostBodyType(TypedDict):
    """OrgsOrgRulesetsPostBody"""

    name: str
    target: NotRequired[Literal["branch", "tag"]]
    enforcement: Literal["disabled", "active", "evaluate"]
    bypass_actors: NotRequired[List[RepositoryRulesetBypassActorType]]
    conditions: NotRequired[
        Union[OrgRulesetConditionsOneof0Type, OrgRulesetConditionsOneof1Type]
    ]
    rules: NotRequired[
        List[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleWorkflowsType,
            ]
        ]
    ]


__all__ = ("OrgsOrgRulesetsPostBodyType",)
