"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0020 import RepositoryType, RepositoryTypeForResponse
from .group_0050 import IssueType, IssueTypeForResponse
from .group_0475 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0476 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0477 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse


class WebhookSubIssuesSubIssueRemovedType(TypedDict):
    """sub-issue removed event"""

    action: Literal["sub_issue_removed"]
    sub_issue_id: float
    sub_issue: IssueType
    sub_issue_repo: RepositoryType
    parent_issue_id: float
    parent_issue: IssueType
    installation: NotRequired[SimpleInstallationType]
    organization: NotRequired[OrganizationSimpleWebhooksType]
    repository: NotRequired[RepositoryWebhooksType]
    sender: NotRequired[SimpleUserType]


class WebhookSubIssuesSubIssueRemovedTypeForResponse(TypedDict):
    """sub-issue removed event"""

    action: Literal["sub_issue_removed"]
    sub_issue_id: float
    sub_issue: IssueTypeForResponse
    sub_issue_repo: RepositoryTypeForResponse
    parent_issue_id: float
    parent_issue: IssueTypeForResponse
    installation: NotRequired[SimpleInstallationTypeForResponse]
    organization: NotRequired[OrganizationSimpleWebhooksTypeForResponse]
    repository: NotRequired[RepositoryWebhooksTypeForResponse]
    sender: NotRequired[SimpleUserTypeForResponse]


__all__ = (
    "WebhookSubIssuesSubIssueRemovedType",
    "WebhookSubIssuesSubIssueRemovedTypeForResponse",
)
