"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0474 import EnterpriseWebhooksType, EnterpriseWebhooksTypeForResponse
from .group_0475 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0476 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0477 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse
from .group_0502 import WebhooksMembershipType, WebhooksMembershipTypeForResponse


class WebhookOrganizationDeletedType(TypedDict):
    """organization deleted event"""

    action: Literal["deleted"]
    enterprise: NotRequired[EnterpriseWebhooksType]
    installation: NotRequired[SimpleInstallationType]
    membership: NotRequired[WebhooksMembershipType]
    organization: OrganizationSimpleWebhooksType
    repository: NotRequired[RepositoryWebhooksType]
    sender: SimpleUserType


class WebhookOrganizationDeletedTypeForResponse(TypedDict):
    """organization deleted event"""

    action: Literal["deleted"]
    enterprise: NotRequired[EnterpriseWebhooksTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    membership: NotRequired[WebhooksMembershipTypeForResponse]
    organization: OrganizationSimpleWebhooksTypeForResponse
    repository: NotRequired[RepositoryWebhooksTypeForResponse]
    sender: SimpleUserTypeForResponse


__all__ = (
    "WebhookOrganizationDeletedType",
    "WebhookOrganizationDeletedTypeForResponse",
)
