"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0448 import EnterpriseWebhooksType, EnterpriseWebhooksTypeForResponse
from .group_0449 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0450 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0451 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse
from .group_0691 import (
    WebhookPackagePublishedPropPackageType,
    WebhookPackagePublishedPropPackageTypeForResponse,
)


class WebhookPackagePublishedType(TypedDict):
    """package published event"""

    action: Literal["published"]
    enterprise: NotRequired[EnterpriseWebhooksType]
    installation: NotRequired[SimpleInstallationType]
    organization: NotRequired[OrganizationSimpleWebhooksType]
    package: WebhookPackagePublishedPropPackageType
    repository: NotRequired[RepositoryWebhooksType]
    sender: SimpleUserType


class WebhookPackagePublishedTypeForResponse(TypedDict):
    """package published event"""

    action: Literal["published"]
    enterprise: NotRequired[EnterpriseWebhooksTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    organization: NotRequired[OrganizationSimpleWebhooksTypeForResponse]
    package: WebhookPackagePublishedPropPackageTypeForResponse
    repository: NotRequired[RepositoryWebhooksTypeForResponse]
    sender: SimpleUserTypeForResponse


__all__ = (
    "WebhookPackagePublishedType",
    "WebhookPackagePublishedTypeForResponse",
)
