"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType
from .group_0448 import EnterpriseWebhooksType
from .group_0449 import SimpleInstallationType
from .group_0450 import OrganizationSimpleWebhooksType
from .group_0451 import RepositoryWebhooksType
from .group_0454 import CheckRunWithSimpleCheckSuiteType


class WebhookCheckRunCreatedType(TypedDict):
    """Check Run Created Event"""

    action: Literal["created"]
    check_run: CheckRunWithSimpleCheckSuiteType
    installation: NotRequired[SimpleInstallationType]
    enterprise: NotRequired[EnterpriseWebhooksType]
    organization: NotRequired[OrganizationSimpleWebhooksType]
    repository: RepositoryWebhooksType
    sender: SimpleUserType


__all__ = ("WebhookCheckRunCreatedType",)
