"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import NotRequired, TypedDict


class ReposOwnerRepoDismissalRequestsSecretScanningAlertNumberPatchResponse200Type(
    TypedDict
):
    """ReposOwnerRepoDismissalRequestsSecretScanningAlertNumberPatchResponse200"""

    dismissal_review_id: NotRequired[int]


__all__ = (
    "ReposOwnerRepoDismissalRequestsSecretScanningAlertNumberPatchResponse200Type",
)
