"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0552 import EnterpriseWebhooksType, EnterpriseWebhooksTypeForResponse
from .group_0553 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0554 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0555 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse
from .group_0571 import WebhooksIssueCommentType, WebhooksIssueCommentTypeForResponse
from .group_0572 import WebhooksChangesType, WebhooksChangesTypeForResponse
from .group_0718 import (
    WebhookIssueCommentEditedPropIssueType,
    WebhookIssueCommentEditedPropIssueTypeForResponse,
)


class WebhookIssueCommentEditedType(TypedDict):
    """issue_comment edited event"""

    action: Literal["edited"]
    changes: WebhooksChangesType
    comment: WebhooksIssueCommentType
    enterprise: NotRequired[EnterpriseWebhooksType]
    installation: NotRequired[SimpleInstallationType]
    issue: WebhookIssueCommentEditedPropIssueType
    organization: NotRequired[OrganizationSimpleWebhooksType]
    repository: RepositoryWebhooksType
    sender: SimpleUserType


class WebhookIssueCommentEditedTypeForResponse(TypedDict):
    """issue_comment edited event"""

    action: Literal["edited"]
    changes: WebhooksChangesTypeForResponse
    comment: WebhooksIssueCommentTypeForResponse
    enterprise: NotRequired[EnterpriseWebhooksTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    issue: WebhookIssueCommentEditedPropIssueTypeForResponse
    organization: NotRequired[OrganizationSimpleWebhooksTypeForResponse]
    repository: RepositoryWebhooksTypeForResponse
    sender: SimpleUserTypeForResponse


__all__ = (
    "WebhookIssueCommentEditedType",
    "WebhookIssueCommentEditedTypeForResponse",
)
