"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import TypedDict, NotRequired


class WebhookStatusPropCommitPropCommitPropCommitterAllof1Type(TypedDict):
    """WebhookStatusPropCommitPropCommitPropCommitterAllof1"""

    date: str
    email: NotRequired[str]
    name: NotRequired[str]


__all__ = ("WebhookStatusPropCommitPropCommitPropCommitterAllof1Type",)
