"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import TypedDict

from .group_0292 import LinkType, LinkTypeForResponse


class PullRequestSimplePropLinksType(TypedDict):
    """PullRequestSimplePropLinks"""

    comments: LinkType
    commits: LinkType
    statuses: LinkType
    html: LinkType
    issue: LinkType
    review_comments: LinkType
    review_comment: LinkType
    self_: LinkType


class PullRequestSimplePropLinksTypeForResponse(TypedDict):
    """PullRequestSimplePropLinks"""

    comments: LinkTypeForResponse
    commits: LinkTypeForResponse
    statuses: LinkTypeForResponse
    html: LinkTypeForResponse
    issue: LinkTypeForResponse
    review_comments: LinkTypeForResponse
    review_comment: LinkTypeForResponse
    self_: LinkTypeForResponse


__all__ = (
    "PullRequestSimplePropLinksType",
    "PullRequestSimplePropLinksTypeForResponse",
)
