"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict

from .group_0108 import (
    RepositoryRulesetBypassActorType,
    RepositoryRulesetBypassActorTypeForResponse,
)
from .group_0127 import (
    RepositoryRuleCreationType,
    RepositoryRuleCreationTypeForResponse,
    RepositoryRuleDeletionType,
    RepositoryRuleDeletionTypeForResponse,
    RepositoryRuleNonFastForwardType,
    RepositoryRuleNonFastForwardTypeForResponse,
    RepositoryRuleRequiredSignaturesType,
    RepositoryRuleRequiredSignaturesTypeForResponse,
)
from .group_0128 import RepositoryRuleUpdateType, RepositoryRuleUpdateTypeForResponse
from .group_0130 import (
    RepositoryRuleRequiredLinearHistoryType,
    RepositoryRuleRequiredLinearHistoryTypeForResponse,
)
from .group_0131 import (
    RepositoryRuleRequiredDeploymentsType,
    RepositoryRuleRequiredDeploymentsTypeForResponse,
)
from .group_0133 import (
    RepositoryRulePullRequestType,
    RepositoryRulePullRequestTypeForResponse,
)
from .group_0135 import (
    RepositoryRuleRequiredStatusChecksType,
    RepositoryRuleRequiredStatusChecksTypeForResponse,
)
from .group_0137 import (
    RepositoryRuleCommitMessagePatternType,
    RepositoryRuleCommitMessagePatternTypeForResponse,
)
from .group_0139 import (
    RepositoryRuleCommitAuthorEmailPatternType,
    RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
)
from .group_0141 import (
    RepositoryRuleCommitterEmailPatternType,
    RepositoryRuleCommitterEmailPatternTypeForResponse,
)
from .group_0143 import (
    RepositoryRuleBranchNamePatternType,
    RepositoryRuleBranchNamePatternTypeForResponse,
)
from .group_0145 import (
    RepositoryRuleTagNamePatternType,
    RepositoryRuleTagNamePatternTypeForResponse,
)
from .group_0147 import (
    RepositoryRuleFilePathRestrictionType,
    RepositoryRuleFilePathRestrictionTypeForResponse,
)
from .group_0149 import (
    RepositoryRuleMaxFilePathLengthType,
    RepositoryRuleMaxFilePathLengthTypeForResponse,
)
from .group_0151 import (
    RepositoryRuleFileExtensionRestrictionType,
    RepositoryRuleFileExtensionRestrictionTypeForResponse,
)
from .group_0153 import (
    RepositoryRuleMaxFileSizeType,
    RepositoryRuleMaxFileSizeTypeForResponse,
)
from .group_0156 import (
    RepositoryRuleWorkflowsType,
    RepositoryRuleWorkflowsTypeForResponse,
)
from .group_0158 import (
    RepositoryRuleCodeScanningType,
    RepositoryRuleCodeScanningTypeForResponse,
)
from .group_0160 import (
    RepositoryRuleCopilotCodeReviewType,
    RepositoryRuleCopilotCodeReviewTypeForResponse,
)
from .group_0164 import (
    OrgRulesetConditionsOneof0Type,
    OrgRulesetConditionsOneof0TypeForResponse,
)
from .group_0165 import (
    OrgRulesetConditionsOneof1Type,
    OrgRulesetConditionsOneof1TypeForResponse,
)
from .group_0166 import (
    OrgRulesetConditionsOneof2Type,
    OrgRulesetConditionsOneof2TypeForResponse,
)


class OrgsOrgRulesetsRulesetIdPutBodyType(TypedDict):
    """OrgsOrgRulesetsRulesetIdPutBody"""

    name: NotRequired[str]
    target: NotRequired[Literal["branch", "tag", "push", "repository"]]
    enforcement: NotRequired[Literal["disabled", "active", "evaluate"]]
    bypass_actors: NotRequired[list[RepositoryRulesetBypassActorType]]
    conditions: NotRequired[
        Union[
            OrgRulesetConditionsOneof0Type,
            OrgRulesetConditionsOneof1Type,
            OrgRulesetConditionsOneof2Type,
        ]
    ]
    rules: NotRequired[
        list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleFilePathRestrictionType,
                RepositoryRuleMaxFilePathLengthType,
                RepositoryRuleFileExtensionRestrictionType,
                RepositoryRuleMaxFileSizeType,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
                RepositoryRuleCopilotCodeReviewType,
            ]
        ]
    ]


class OrgsOrgRulesetsRulesetIdPutBodyTypeForResponse(TypedDict):
    """OrgsOrgRulesetsRulesetIdPutBody"""

    name: NotRequired[str]
    target: NotRequired[Literal["branch", "tag", "push", "repository"]]
    enforcement: NotRequired[Literal["disabled", "active", "evaluate"]]
    bypass_actors: NotRequired[list[RepositoryRulesetBypassActorTypeForResponse]]
    conditions: NotRequired[
        Union[
            OrgRulesetConditionsOneof0TypeForResponse,
            OrgRulesetConditionsOneof1TypeForResponse,
            OrgRulesetConditionsOneof2TypeForResponse,
        ]
    ]
    rules: NotRequired[
        list[
            Union[
                RepositoryRuleCreationTypeForResponse,
                RepositoryRuleUpdateTypeForResponse,
                RepositoryRuleDeletionTypeForResponse,
                RepositoryRuleRequiredLinearHistoryTypeForResponse,
                RepositoryRuleRequiredDeploymentsTypeForResponse,
                RepositoryRuleRequiredSignaturesTypeForResponse,
                RepositoryRulePullRequestTypeForResponse,
                RepositoryRuleRequiredStatusChecksTypeForResponse,
                RepositoryRuleNonFastForwardTypeForResponse,
                RepositoryRuleCommitMessagePatternTypeForResponse,
                RepositoryRuleCommitAuthorEmailPatternTypeForResponse,
                RepositoryRuleCommitterEmailPatternTypeForResponse,
                RepositoryRuleBranchNamePatternTypeForResponse,
                RepositoryRuleTagNamePatternTypeForResponse,
                RepositoryRuleFilePathRestrictionTypeForResponse,
                RepositoryRuleMaxFilePathLengthTypeForResponse,
                RepositoryRuleFileExtensionRestrictionTypeForResponse,
                RepositoryRuleMaxFileSizeTypeForResponse,
                RepositoryRuleWorkflowsTypeForResponse,
                RepositoryRuleCodeScanningTypeForResponse,
                RepositoryRuleCopilotCodeReviewTypeForResponse,
            ]
        ]
    ]


__all__ = (
    "OrgsOrgRulesetsRulesetIdPutBodyType",
    "OrgsOrgRulesetsRulesetIdPutBodyTypeForResponse",
)
