"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing_extensions import NotRequired, TypedDict


class BillingUsageSummaryReportGheType(TypedDict):
    """BillingUsageSummaryReportGhe"""

    time_period: BillingUsageSummaryReportGhePropTimePeriodType
    enterprise: str
    organization: NotRequired[str]
    repository: NotRequired[str]
    product: NotRequired[str]
    sku: NotRequired[str]
    cost_center: NotRequired[BillingUsageSummaryReportGhePropCostCenterType]
    usage_items: list[BillingUsageSummaryReportGhePropUsageItemsItemsType]


class BillingUsageSummaryReportGhePropTimePeriodType(TypedDict):
    """BillingUsageSummaryReportGhePropTimePeriod"""

    year: int
    month: NotRequired[int]
    day: NotRequired[int]


class BillingUsageSummaryReportGhePropCostCenterType(TypedDict):
    """BillingUsageSummaryReportGhePropCostCenter"""

    id: str
    name: str


class BillingUsageSummaryReportGhePropUsageItemsItemsType(TypedDict):
    """BillingUsageSummaryReportGhePropUsageItemsItems"""

    product: str
    sku: str
    unit_type: str
    price_per_unit: float
    gross_quantity: float
    gross_amount: float
    discount_quantity: float
    discount_amount: float
    net_quantity: float
    net_amount: float


__all__ = (
    "BillingUsageSummaryReportGhePropCostCenterType",
    "BillingUsageSummaryReportGhePropTimePeriodType",
    "BillingUsageSummaryReportGhePropUsageItemsItemsType",
    "BillingUsageSummaryReportGheType",
)
