"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType, SimpleUserTypeForResponse
from .group_0020 import RepositoryType, RepositoryTypeForResponse
from .group_0200 import IssueType, IssueTypeForResponse
from .group_0553 import SimpleInstallationType, SimpleInstallationTypeForResponse
from .group_0554 import (
    OrganizationSimpleWebhooksType,
    OrganizationSimpleWebhooksTypeForResponse,
)
from .group_0555 import RepositoryWebhooksType, RepositoryWebhooksTypeForResponse


class WebhookIssueDependenciesBlockingRemovedType(TypedDict):
    """blocking issue removed event"""

    action: Literal["blocking_removed"]
    blocked_issue_id: NotRequired[float]
    blocked_issue: NotRequired[IssueType]
    blocked_issue_repo: NotRequired[RepositoryType]
    blocking_issue_id: NotRequired[float]
    blocking_issue: NotRequired[IssueType]
    installation: NotRequired[SimpleInstallationType]
    organization: OrganizationSimpleWebhooksType
    repository: RepositoryWebhooksType
    sender: SimpleUserType


class WebhookIssueDependenciesBlockingRemovedTypeForResponse(TypedDict):
    """blocking issue removed event"""

    action: Literal["blocking_removed"]
    blocked_issue_id: NotRequired[float]
    blocked_issue: NotRequired[IssueTypeForResponse]
    blocked_issue_repo: NotRequired[RepositoryTypeForResponse]
    blocking_issue_id: NotRequired[float]
    blocking_issue: NotRequired[IssueTypeForResponse]
    installation: NotRequired[SimpleInstallationTypeForResponse]
    organization: OrganizationSimpleWebhooksTypeForResponse
    repository: RepositoryWebhooksTypeForResponse
    sender: SimpleUserTypeForResponse


__all__ = (
    "WebhookIssueDependenciesBlockingRemovedType",
    "WebhookIssueDependenciesBlockingRemovedTypeForResponse",
)
