"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

from typing import Literal
from typing_extensions import NotRequired, TypedDict

from .group_0003 import SimpleUserType
from .group_0494 import EnterpriseWebhooksType
from .group_0495 import SimpleInstallationType
from .group_0496 import OrganizationSimpleWebhooksType
from .group_0497 import RepositoryWebhooksType
from .group_0544 import WebhooksSponsorshipType
from .group_0545 import WebhooksChanges8Type


class WebhookSponsorshipPendingTierChangeType(TypedDict):
    """sponsorship pending_tier_change event"""

    action: Literal["pending_tier_change"]
    changes: WebhooksChanges8Type
    effective_date: NotRequired[str]
    enterprise: NotRequired[EnterpriseWebhooksType]
    installation: NotRequired[SimpleInstallationType]
    organization: NotRequired[OrganizationSimpleWebhooksType]
    repository: NotRequired[RepositoryWebhooksType]
    sender: SimpleUserType
    sponsorship: WebhooksSponsorshipType


__all__ = ("WebhookSponsorshipPendingTierChangeType",)
