"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

python -m codegen && isort . && black .

See https://github.com/github/rest-api-description for more information.
"""

from typing import Dict, Type, Union
from typing_extensions import Annotated, TypeAlias

from pydantic import Field

from githubkit.utils import TaggedUnion
from githubkit.compat import GitHubModel

from ..models import (
    WebhookSecretScanningAlertCreated,
    WebhookSecretScanningAlertRevoked,
    WebhookSecretScanningAlertReopened,
    WebhookSecretScanningAlertResolved,
)

Event: TypeAlias = Annotated[
    Union[
        WebhookSecretScanningAlertCreated,
        WebhookSecretScanningAlertReopened,
        WebhookSecretScanningAlertResolved,
        WebhookSecretScanningAlertRevoked,
    ],
    Field(discriminator="action"),
]

SecretScanningAlertEvent: TypeAlias = Event

action_types: Dict[str, Type[GitHubModel]] = {
    "created": WebhookSecretScanningAlertCreated,
    "reopened": WebhookSecretScanningAlertReopened,
    "resolved": WebhookSecretScanningAlertResolved,
    "revoked": WebhookSecretScanningAlertRevoked,
}

secret_scanning_alert_action_types = action_types

__all__ = (
    "Event",
    "SecretScanningAlertEvent",
    "action_types",
    "secret_scanning_alert_action_types",
)
